"""Add unique supermarket/product constraint

Revision ID: e664ea53c26f
Revises: 0adb5ca99abb
Create Date: 2025-11-21 17:31:40.291399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e664ea53c26f'
down_revision: Union[str, Sequence[str], None] = '0adb5ca99abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_market_product', 'products', ['supermarket_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_market_product', 'products', type_='unique')
    # ### end Alembic commands ###
